// Mapping of ISO country codes to country names
export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
    "AUS": "Australia",
    "AUT": "Austria",
    "BEL": "Belgium",
    "CAN": "Canada",
    "CHL": "Chile",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CZE": "Czech Republic",
    "DNK": "Denmark",
    "EST": "Estonia",
    "FIN": "Finland",
    "FRA": "France",
    "DEU": "Germany",
    "GRC": "Greece",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IRL": "Ireland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JPN": "Japan",
    "KOR": "South Korea",
    "LVA": "Latvia",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MEX": "Mexico",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "POL": "Poland",
    "PRT": "Portugal",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "ESP": "Spain",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "TUR": "Turkey",
    "GBR": "United Kingdom",
    "USA": "United States",
    "G7": "G7",
    "G20": "G20",
    "EA20": "Euro Area (20 countries)",
    "EU27_2020": "European Union (27 countries)",
    "OECD": "OECD - Total",
    "OECDE": "OECD - Europe",
    "ARG": "Argentina",
    "BRA": "Brazil",
    "BGR": "Bulgaria",
    "CHN": "China",
    "HRV": "Croatia",
    "IND": "India",
    "IDN": "Indonesia",
    "RUS": "Russia",
    "SAU": "Saudi Arabia",
    "ZAF": "South Africa",
};

export const getCountryName = (countryCode: string): string => {
    return COUNTRY_CODE_TO_NAME[countryCode] || countryCode;
};

